Repository ARCANEDEV/LogViewer, pull requests merged in 2018-10, with the labels that each got.

#243 Fixing the compact issue with missing variables
  resources/views/bootstrap-3/show.blade.php
  resources/views/bootstrap-4/show.blade.php
  src/Http/Controllers/LogViewerController.php
  src/Utilities/LogChecker.php
Labels: fixed

#245 [4.4] Fixing the compact issue with missing variables
  resources/views/show.blade.php
  src/Http/Controllers/LogViewerController.php
  src/Utilities/LogChecker.php
Labels: fixed

#248 Adding the results count for the search form
  resources/views/bootstrap-3/show.blade.php
  resources/views/bootstrap-4/show.blade.php
Labels: feature request

#249 Update README.md
  README.md
Labels: docs
