Repository ARCANEDEV/LogViewer, pull requests merged in 2018-04, with the labels that each got.

#204 Added Romanian Translation
  resources/lang/ro/general.php
Labels: translation

#205 ENV config for Laravel 5.5 and below
  _docs/1.Installation-and-Setup.md
Labels: docs

#207 Feature clear all logs command
  composer.json
  src/Commands/ClearLogsCommand.php
  src/LogViewer.php
  src/Providers/CommandsServiceProvider.php
  src/Utilities/Factory.php
  tests/Commands/ClearLogsCommandTest.php
  tests/Providers/CommandsServiceProviderTest.php
  tests/TestCase.php
Labels: feature request
