Repository ARCANEDEV/LogViewer, pull requests merged in 2019-10, with the labels that each got.

#295 Updating the package
  README.md
  _docs/0.Home.md
  _docs/1.Installation-and-Setup.md
  _docs/2.Configuration.md
  composer.json
  config/log-viewer.php
  src/Facades/LogMenu.php
  src/Facades/LogStyler.php
  src/Facades/LogViewer.php
  src/LogViewer.php
  src/LogViewerServiceProvider.php
  src/Providers/CommandsServiceProvider.php
  src/Providers/UtilitiesServiceProvider.php
  tests/LogViewerServiceProviderTest.php
  tests/Providers/CommandsServiceProviderTest.php
  tests/Providers/UtilitiesServiceProviderTest.php
Labels: enhancement

#296 Defer the service provider
  src/LogViewerServiceProvider.php
  tests/LogViewerServiceProviderTest.php
Labels: enhancement

#298 Fixing the deferred provider
  src/LogViewerServiceProvider.php
  src/Providers/RouteServiceProvider.php
  src/Providers/ServicesProvider.php
  tests/LogViewerServiceProviderTest.php
  tests/Providers/UtilitiesServiceProviderTest.php
Labels: fixed

#299 Defer properly the services + cleaning
  composer.json
  src/LogViewerServiceProvider.php
  src/Providers/DeferredServicesProvider.php
  tests/Providers/DeferredServicesProviderTest.php
  tests/TestCase.php
Labels: enhancement

#304 Fix LogViewer's version
  src/LogViewer.php
Labels: enhancement

#307 Allow for case insensitive search query
  src/Http/Controllers/LogViewerController.php
  tests/RoutesTest.php
Labels: feature request

#308 Minor updates
  .travis.yml
  src/Http/Controllers/LogViewerController.php
  src/LogViewer.php
Labels: enhancement

#309 Add Malay Translation
  README.md
  resources/lang/ms/general.php
  resources/lang/ms/levels.php
  tests/TestCase.php
Labels: translation

#310 Completing the `hu` translation with google translate :)
  resources/lang/hu/general.php
Labels: translation
